# Generated by Django 4.2.1 on 2023-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_TipoUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='TipoUsuario',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
