# Generated by Django 4.2.1 on 2023-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_remove_usuario_id_tipousuario_usuario_tipousuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('asunto', models.CharField(max_length=3000)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
