# Generated by Django 4.2.1 on 2023-06-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
