# Generated by Django 4.2.1 on 2023-06-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0005_alter_noticia_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
